name: "Test: minos-discovery-kong"

on:
  push:
    branches:
      - main
      - '*.*.x'
  pull_request:
    paths:
      - 'packages/plugins/minos-discovery-kong/**'
      - 'packages/core/minos-microservice-networks/**'
      - 'packages/core/minos-microservice-common/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-buster
    services:
      postgres:
        image: postgres:9.5
        env:
            POSTGRES_DB: kong
            POSTGRES_USER: kong
            POSTGRES_PASSWORD: kong
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    defaults:
      run:
        working-directory: packages/plugins/minos-discovery-kong

    steps:
      - name: Download Kong dependencies pre-install
        run: curl -Lo kong-enterprise-edition-2.8.0.0.all.deb "https://download.konghq.com/gateway-2.x-ubuntu-$(lsb_release -cs)/pool/all/k/kong-enterprise-edition/kong_2.8.0.0_all.deb"

      - name: Install Kong package
        run: sudo dpkg -i kong-enterprise-edition-2.8.0.0.all.deb

      - name: Set env variables
        run: |
          echo "KONG_DATABASE=postgres" >> $GITHUB_ENV
          echo "KONG_PG_DATABASE=kong" >> $GITHUB_ENV
          echo "KONG_PG_HOST=postgres" >> $GITHUB_ENV
          echo "KONG_PG_USER=kong" >> $GITHUB_ENV
          echo "KONG_PG_PASSWORD=kong" >> $GITHUB_ENV
          echo "KONG_ADMIN_ACCESS_LOG=/dev/stdout" >> $GITHUB_ENV
          echo "KONG_ADMIN_ERROR_LOG=/dev/stderr" >> $GITHUB_ENV
          echo "KONG_PROXY_LISTEN=0.0.0.0:8000" >> $GITHUB_ENV
          echo "KONG_ADMIN_LISTEN=0.0.0.0:8001" >> $GITHUB_ENV
          echo "KONG_PROXY_ACCESS_LOG=/dev/stdout" >> $GITHUB_ENV
          echo "KONG_PROXY_ERROR_LOG=/dev/stderr" >> $GITHUB_ENV
          echo "KONG_LOG_LEVEL=debug" >> $GITHUB_ENV

      - name: Kong Migration
        run: kong migrations bootstrap && kong migrations up && kong migrations finish

      - name: Kong Start
        run: kong start

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: make install

      - name: Lint package
        run: make lint

      - name: Test package with coverage
        run: make coverage

      - name: Publish coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/plugins/minos-discovery-kong/coverage.xml
          fail_ci_if_error: true

      - name: Generate documentation
        run: make docs

      - name: Generate build
        run: make dist

      - name: Stop containers
        if: always()
        run: docker-compose -f "./tests/docker-compose.yml" down
